# Generated by Django 5.2.14 on 2026-08-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0002_product_order_orderitem_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
