# Generated by Django 5.2.14 on 2026-09-03 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0004_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hotel_management.reservation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hotel_management.room'),
        ),
    ]
